###
GET http://localhost:8080/api/note

###
GET http://localhost:8080/api/note/20

###
POST http://localhost:8080/api/note
Content-Type: application/json

{
  "title": "just note title",
  "content": "just note content"
}

###
PUT http://localhost:8080/api/note/3
Content-Type: application/json

{
  "title": "just note title update3",
  "content": "just note content update33"
}

###
DELETE http://localhost:8080/api/note/20