###
GET http://localhost:8080/api/note

###
GET http://localhost:8080/api/note/20

###
POST http://localhost:8080/api/note
Content-Type: application/json

{
  "content": "just note value"
}

###
PUT http://localhost:8080/api/note/20
Content-Type: application/json

{
  "content": "just note update3333"
}

###
DELETE http://localhost:8080/api/note/20