DROP TABLE IF EXISTS NOTES CASCADE;
DROP TABLE IF EXISTS NOTE_SNAPSHOTS CASCADE;

CREATE TABLE NOTES
(
    ID                 SERIAL PRIMARY KEY,
    TITLE              VARCHAR(64) NOT NULL UNIQUE,
    CONTENT            VARCHAR(256) NOT NULL,
    VERSION            BIGINT NOT NULL,
    DELETED_DATE_TIME            TIMESTAMP,
    CREATED_DATE_TIME            TIMESTAMP,
    MODIFIED_DATE_TIME           TIMESTAMP
);

CREATE TABLE NOTE_SNAPSHOTS
(
    ID                 SERIAL PRIMARY KEY,
    TITLE              VARCHAR(64) NOT NULL,
    CONTENT            VARCHAR(256) NOT NULL,
    VERSION            BIGINT NOT NULL,
    NOTE_ID            INTEGER REFERENCES NOTES(ID),
    MODIFIED_DATE_TIME           TIMESTAMP
);

DROP SEQUENCE IF EXISTS hibernate_sequence CASCADE;
CREATE SEQUENCE public.hibernate_sequence
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

DROP SEQUENCE IF EXISTS NOTES_ID_SEQ CASCADE;
CREATE SEQUENCE public.NOTES_ID_SEQ
    START WITH 20
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

    DROP SEQUENCE IF EXISTS NOTE_SNAPSHOTS_ID_SEQ CASCADE;
CREATE SEQUENCE public.NOTE_SNAPSHOTS_ID_SEQ
    START WITH 20
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

ALTER TABLE ONLY NOTES ALTER COLUMN ID SET DEFAULT nextval('NOTES_ID_SEQ'::regclass);
ALTER TABLE ONLY NOTE_SNAPSHOTS ALTER COLUMN ID SET DEFAULT nextval('NOTE_SNAPSHOTS_ID_SEQ'::regclass);